'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var generateCustomTemplate = function generateCustomTemplate(templateOptions) {
  return '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n<html\n  ' + (templateOptions.lang ? 'lang="' + templateOptions.lang + '"' : '') + '\n  dir="' + templateOptions.dir + '"\n  xmlns="http://www.w3.org/1999/xhtml"\n  xmlns:v="urn:schemas-microsoft-com:vml"\n  xmlns:o="urn:schemas-microsoft-com:office:office">\n  <head>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n    <meta http-equiv="X-UA-Compatible" content="IE=edge" />\n    <meta name="viewport" content="width=device-width"/>\n\n    <title>' + templateOptions.title + '</title>\n\n    <style type="text/css">\n      ' + templateOptions.headCSS + '\n\n      #__bodyTable__ {\n        margin: 0;\n        padding: 0;\n        width: 100% !important;\n      }\n    </style>\n\n    <!--[if gte mso 9]>\n      <xml>\n        <o:OfficeDocumentSettings>\n          <o:AllowPNG/>\n          <o:PixelsPerInch>96</o:PixelsPerInch>\n        </o:OfficeDocumentSettings>\n      </xml>\n    <![endif]-->\n  </head>\n  <body bgcolor="#f7f6f5" width="100%" style="-webkit-font-smoothing: antialiased; width:100% !important; background:#f7f6f5;-webkit-text-size-adjust:none; margin:0; padding:0; min-width:100%; direction: ' + templateOptions.dir + ';">\n    <table cellpadding="0" cellspacing="0" bgcolor="#f7f6f5" id="__bodyTable__" width="100%" style="-webkit-font-smoothing: antialiased; width:100% !important; background:#FFFFFF;-webkit-text-size-adjust:none; margin:0; padding:0; min-width:100%">\n      <tr>\n        <td align="center">\n          <span style="display: none !important; color: #FFFFFF; margin:0; padding:0; font-size:1px; line-height:1px;">' + templateOptions.previewText + '</span>\n          ' + templateOptions.bodyContent + '\n        </td>\n      </tr>\n    </table>\n  </body>\n</html>';
};

exports.default = generateCustomTemplate;